### ISSUE TITLE
Error when navigating to Ubuntu Budgie's contribute page

### ISSUE THREAD

**Issue by manderso7** [KillYourFM/contribute-foss#12]
When navigating to the Ubuntu Budgie link in the "Get Involved" section:
the link sends you to a page with the text: 
"No route found for "GET /opportunities" (from "https://github.com/KillYourFM/contribute-foss")". This is the correct link:
https://discourse.ubuntubudgie.org/c/Get-Involved?status=open

**Comment by LinuxForEveryone** [comment]
Fixed by @bashfulrobot, thanks!
