### ISSUE TITLE
Proposal: Twitter Rotation Curation Account "@IMakeFoss"

### ISSUE THREAD

**Issue by Knochestolle** [KillYourFM/contribute-foss#14]
A Twitter rotation curation account [1] where people who contribute to FOSS can introduce themselves on a weekly basis, similar to @RealScientists.
The idea is that those who are intensively involved with FOSS can present their projects and their person, answer questions and thus arouse interest in getting involved.

References
[1] https://en.wikipedia.org/wiki/Rotation_Curation
[2] https://twitter.com/realscientists

**Comment by LinuxForEveryone** [comment]
As someone whose marketing senses are always tingling, I love this idea @Knochestolle. It may exist outside the scope of THIS particular effort on GitHub, but it's worth exploring tying it together. 

Some considerations:

1.Twitter account name has to be shorter, readable, and easy to write. (For example, do you prefer writing  "Pop!_OS" or "Pop OS" :D 
2. Where would Twitter bio links lead? Would they rotate based on who is "on the mic" that week? Or lead to this Wiki? 
3. How is scheduling assigned? How often do they rotate in and out? 
4. How do we moderate the Twitter account to ensure things don't get inappropriate, toxic or off-topic?
5. Does this already exist?

**Comment by Knochestolle** [comment]
I'm glad you like the idea @KillYourFM. Yes, I would definitely associate it with this initiative to direct people here, to arouse interest in FOSS and to show ways in which one can contribute to FOSS.
I've known one of the moderators of realscientists for many years and I've talked to him today about how they do it.

To your considerations:
1. Yes, you're absolutely right. The account name "@I_Contribute_To_FOSS" was just a proposal to make the idea clear. Other proposals would be "People Behind FOSS", "That's FOSS", "I make FOSS" ...
2. To this wiki or a blog like that of the realscientists [1].
3. The planning is done by moderators. The rotation is weekly.
4. Prior arrangement (we have to discuss this) and we make completely clear that we take over the account with offence against rules.
5. I don't know of any rotation account to FOSS.

[1] http://realscientists.org

**Comment by LinuxForEveryone** [comment]
For the record, I think @IMakeFoss is perfect and we should get it created using an email all mods would have access to. Perhaps something on ProtonMail? 

Thanks for addressing my concerns. 

Does anyone else have concerns or suggestions? I think we should kick the tires on this.

**Comment by Knochestolle** [comment]
Then we do that? Should I create the Twitter account? I would recommend posteo as email provider [1], completely anonymous, encrypted, exclusive use of open source software. I'd cover the running costs. I have been using posteo myself for 6 years and am very satisfied.

Procedure for the realscientists:
1. Weekly change of curator on Sunday
2. New curator receives questionnaire on his bio and our rules (we have to discuss this)
3. Curator receives new password for our Twitter account
4. Password is regenerated before the next change

Our next steps:
1. Schedule, moderation (I can take over the beginning)
2. Discuss our preliminary conditions and questionnaire for the weekly curators
3. When do we want to start
4. Advertising this new project in advance
5. External blog or wiki here? For completely inexperienced new people interested in FOSS a blog might feel better? I could do a WordPress installation on a new webspace. Here I have good experiences with Uberspace [2]. I would also bear the costs and register the domain as imakefoss.org. 
6. Find the first curator

[1] https://posteo.de/en/site/features#leistungenkonditionen
[2] https://uberspace.de/en/

**Comment by LinuxForEveryone** [comment]
**Re: Posteo / email:**
Surely we can find a cost-free solution, yes? I can't imagine it will demand much storage space. 

**Re: Blog platform**

I think a simple, clean, public-facing blog is the right approach. We want to broaden the appeal and readability as much as possible. I'm OK with Wordpress if you're certain it's secure (I've heard various nasty things. I personally use Ghost and find it much easier to manage from a content and appearance perspective, but it's also more restricted in terms of appearance options). If you're bearing the brunt of the workload in that regard, though, I defer to you and acknowledge that what you're comfortable with is important. 

**Re: Twitter account**

Yes, let's fire up @IMakeFOSS! 

**Miscellaneous:** 

Once we have the necessary foundation (Twitter account, blog, email), let's start putting the word out on social media and recruit the first curator. Can a contact form be created on the blog that allows people to volunteer and submit their information? Maybe we can pipe that data into a spreadsheet to keep track....

**Comment by Knochestolle** [comment]
Then I register email address, Twitter account and domain. And I check alternatives to WordPress.

**Blog**
I have been responsible for 2 WordPress installations for several years and have had no problems so far. In my opinion, the design and extension possibilities of WordPress are very good. We could also consider in the future whether we could also open the job/task portal via this site?
But if someone has other suggestions? How much does Ghost cost per month?

**Contact form**
Yes! The contact page for volunteers could be designed openly and the questionnaire for the already planned curators could be sent via a password-protected site.

**Spreadsheet**
Yes, good idea. We should check if we can elegantly implement this in the moderator area of the blog.

**Open task**
Who could design a nice logo for the blog and the Twitter account (profile picture and banner)?

**Comment by LinuxForEveryone** [comment]
> How much does Ghost cost per month?

Ghost is free. It's what I use for [DitchWindows.com](url), and have it running on a one-click Digital Ocean droplet. 

> Who could design a nice logo for the blog and the Twitter account (profile picture and banner)?

I'll put the word out :D

**Comment by Knochestolle** [comment]
OK. Thank you! I'll see what's possible with Ghost. The extensibility with input forms etc. would be great. I was once on ghost.org, there the prices start at 29$/month? I've never worked with Ghost before. Then you use a standard Digital Ocean droplet like this: https://marketplace.digitalocean.com/apps/wordpress? Looks really good! Simple and quick to set up, I guess. The "Uberspace" I use for other projects is much more open with more possibilities, but also more maintenance-intensive and therefore riskier. You have to do everything from scratch.

That would be great if we could find someone who could make us a nice logo, which we could also use for the colors and fonts of the blog page as a style.

**Comment by LinuxForEveryone** [comment]
> OK. Thank you! I'll see what's possible with Ghost. The extensibility with input forms etc. would be great. I was once on ghost.org, there the prices start at 29$/month? 
> 
That's for the Ghost(Pro) platform, which is fully managed on their own infrastructure.

**Comment by LinuxForEveryone** [comment]
Update: I've started putting the word out for a logo designer.

**Comment by LinuxForEveryone** [comment]
Update: @IMakeFOSS has been created on Twitter, and the domain imakefoss.org is live, though it's just a generic landing page for now.

**Comment by LinuxForEveryone** [comment]
Question: Shall we have developers contact us directly on Twitter? Where does an email go if they were to use a contact form on the .org site?

**Comment by LinuxForEveryone** [comment]
I Make FOSS has been alive and kicking for months, thanks to this very issue being opened! AWESOME! Closing it up, thank you1
