### ISSUE TITLE
Some things to add

### ISSUE THREAD

**Issue by maor26** [KillYourFM/contribute-foss#21]
Some Projects that could be added

**ADDED:**
Desktop Environments:
Budgie - https://github.com/solus-project/budgie-desktop

Video Editing software:
Openshot - https://www.openshot.org/
KdenLive - https://kdenlive.org/en/

Design software:
AkiraUX - https://github.com/akiraux/Akira
Inkscape- https://inkscape.org/
Krita - https://krita.org/en/get-involved/overview/
DarkTable - https://www.darktable.org/development/
Blender - https://www.blender.org/get-involved/

Game engines:
Godot - https://godotengine.org/

Open Source GPU Driver:
FreeDreno - https://github.com/freedreno/freedreno

Monitoring/Overclocking software for AMD GPUs:
WattmanGTK - https://github.com/BoukeHaarsma23/WattmanGTK
radeon-profile - https://github.com/marazmista/radeon-profile

**Comment by LinuxForEveryone** [comment]
Thanks a ton @maor26, I'll get these added!

**Comment by maor26** [comment]
happy to help @KillYourFM .
I really like your idea, and I also wanted to start contributing more to projects I like and/or use.
Keep doing an awesome job with your articles and the choose linux podcast!

**Comment by LinuxForEveryone** [comment]
Added all and closing.
