### ISSUE TITLE
Proposal: Create guide on how to contribute to this project

### ISSUE THREAD

**Issue by LinuxForEveryone** [KillYourFM/contribute-foss#22]
We need a simple, short and easy to understand document that explains how to contribute to this project (think "explain it like I'm 5"). 

We may want to create this as part of a larger document that's built to assist the overall projects. 

Considerations for that:

-What are the most pressing needs? 
-How can people best share / promote this project to expand participation?
-Are there other platforms where people can suggest enhancements or will this always live on GitHub?

Please add your thoughts.

**Comment by TeamLinux01** [comment]
GitHub may not be the best place for people to edit this information, but I do think it will help people learn a bit about git and how GitHub works. With that knowledge, they may look into other GitHub projects or other Version Control Systems.

We probably should have some links or basic explanation of how to use git/github, so people don't feel left out do to a barrier of entry using the platform.

**Comment by thefenriswolf** [comment]
@KillYourFM there you go https://github.com/KillYourFM/contribute-foss/pull/39
