### ISSUE TITLE
Consider following the Awesome style of documenting these things

### ISSUE THREAD

**Issue by adds68** [KillYourFM/contribute-foss#4]
There is a project called [Awesome](https://github.com/sindresorhus/awesome), maybe it would be good to follow this style of documentation so the list can be added to that index? 

If so i can spend some time trying to port the current content as this is an awesome idea! :)

**Comment by LinuxForEveryone** [comment]
> There is a project called [Awesome](https://github.com/sindresorhus/awesome), maybe it would be good to follow this style of documentation so the list can be added to that index?
> 
> If so i can spend some time trying to port the current content as this is an awesome idea! :)

I just browsed a couple awesome lists such as [this one](https://github.com/trimstray/the-book-of-secret-knowledge), and it's definitely a _clean_ looking way to present information. 

I appreciate the suggestion as I'm flying blind here. Let me defer to people who know what they're doing. If you're willing to lead the charge in this regard, I'm all for it! What are the first steps?

**Comment by adds68** [comment]
I understand, I was wondering mainly if you thought it was a good idea. I know this guide is not *just* a list of links, but it seems some of the list do contain more information.

The first step would be to restructure the README and then try and section out the main article into sections and link them in the README? 

If Awesome is not usable here I am also up for restructuring the markdown \o/

**Comment by LinuxForEveryone** [comment]
> If Awesome is not usable here I am also up for restructuring the markdown \o/

Thank you! Not to derail your idea, but how do you feel about [GitBook](https://www.gitbook.com/)?

**Comment by adds68** [comment]
wow i've never heard of that, it looks really nice.

My only issue would be that you may increase the barrier of entry by using something external to Github?
