### ISSUE TITLE
GitBook

### ISSUE THREAD

**Issue by LinuxForEveryone** [KillYourFM/contribute-foss#5]
What are everyone's thoughts on using GitBook (suggested by @tmray)? It certainly seems like an elegant and modern solution. And it syncs with GitHub.

**Comment by tmray** [comment]
Well, you know my vote :shipit:

**Comment by LinuxForEveryone** [comment]
It looks like you can only have 2 users for a free account though? :/

**Comment by tmray** [comment]
True. I forgot about that. 

Here is my thought though, it syncs with GitHub. So think of it like a publication in this way.

You set up the main template in Gitbook. Like you would a website.
Sync it up with Github. People write docs and edit them in Github kinda like using a cms. 
Those get pushed into Gitbook where you control the final content and layout like an editor would.
And the end user experience is more accessible to read. 

Just an option. Either way :)

**Comment by LinuxForEveryone** [comment]
> Here is my thought though, it syncs with GitHub. So think of it like a publication in this way.
> 
> You set up the main template in Gitbook. Like you would a website.
> Sync it up with Github. People write docs and edit them in Github kinda like using a cms.
> Those get pushed into Gitbook where you control the final content and layout like an editor would.
> And the end user experience is more accessible to read.

When you present it that way, it sounds perfect! Ok let's keep cranking away here and I'll start exploring that!
