### ISSUE TITLE
Add Open Source License

### ISSUE THREAD

**Issue by tmray** [KillYourFM/contribute-foss#6]
I just wanted to suggest adding an open source license to the project since it is about open source software :)

**How to:**
* Create a file just called `LICENSE`
* To the right of the file name field, click **Choose a license template**.
* Pick what license you think is best

For more info, the full process is in the Github support section https://help.github.com/en/articles/adding-a-license-to-a-repository

**Comment by LinuxForEveryone** [comment]
Thank you @tmray, an obviously excellent idea! Going to propose a GPLv3 license.

**Comment by adds68** [comment]
Possibly something related to documentation: https://dreamsongs.com/IHE/IHE-50.html ?

**Comment by omicron-b** [comment]
Choosing GPL may block #4 though. https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license

**Comment by LinuxForEveryone** [comment]
> Choosing GPL may block #4 though. https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license

Thanks, I'll research this a bit more.

**Comment by tmray** [comment]
Since this is mainly documentation and not software, you could use a creative commons license. You can copy and paste the info into the `LICENSE` document and it recognizes it as a CC license in Github.

For example, you could copy and paste from the raw files here:

**CC-BY-SA**
https://choosealicense.com/licenses/cc-by-sa-4.0/

**CC-BY**
https://choosealicense.com/licenses/cc-by-4.0/

**Comment by omicron-b** [comment]
or you can download a markdown version of CC license from [this repo](https://github.com/idleberg/Creative-Commons-Markdown) and upload  
I prefer this method for my works because markdown looks better for someone who may open it in GitHub

**Comment by tmray** [comment]
Either/Or. I'm just saying a CC license could be an option since it's text-based.

**Comment by LinuxForEveryone** [comment]
Thank you to everyone who offered feedback here. I've changed the [LICENSE](https://github.com/KillYourFM/contribute-foss/blob/master/LICENSE) to a Creative Commons BY-SA 4.0 International license.
