### ISSUE TITLE
Mapping a web site to the Github

### ISSUE THREAD

**Issue by TeamLinux01** [KillYourFM/contribute-foss#67]
I was thinking that we should think about rolling out a complete website for this project.

We could set it up like System76 links to their github, such as:
https://support.system76.com/articles/
https://github.com/system76/docs/tree/gh-pages/_articles

Just throwing out the idea.

**Comment by LinuxForEveryone** [comment]
Thanks @TeamLinux01 for the suggestion.  We'll be integrating this as a Wiki page into the upcoming Linux For Everyone site redesign.
